#!/usr/bin/env node
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve, join } from 'node:path';
const upstream=resolve(process.argv[2]||process.env.BF6_ANALYZER_DIR||'.upstream/bf6-analyzer');
const outDir=resolve(process.argv[3]||'data');
const expectedFile=resolve(process.argv[4]||'data/sniper-audit.json');
const weapons=JSON.parse(await readFile(join(upstream,'data/weapons.json'),'utf8'));
const atts=JSON.parse(await readFile(join(upstream,'data/attachments.json'),'utf8'));
const ammo=JSON.parse(await readFile(join(upstream,'data/ammo.json'),'utf8'));
const expected=JSON.parse(await readFile(expectedFile,'utf8'));
const errors=[],warnings=[],checked={}; let lowBodyChecks=0,upstreamCurveChecks=0,knownGoodChecks=0;
function alias(v){return String(v||'').toLowerCase().replace(/[^a-z0-9]/g,'');}
function findWeapon(id,name){return weapons.find(w=>alias(w.id)===alias(id))||weapons.find(w=>alias(w.name)===alias(name));}
function near(a,b,t){return Number.isFinite(Number(a))&&Number.isFinite(Number(b))&&Math.abs(Number(a)-Number(b))<=t;}
function btkFor(d){return Number(d)>0?Math.ceil((100-1e-9)/Number(d)):null;}
function ttkFromInterval(i,b){return b<=1?0:Math.round((b-1)*Number(i));}
function linearDamage(curve,d){const p=(curve||[]).map(x=>({r:Number(x.r),d:Number(x.d)})).filter(x=>Number.isFinite(x.r)&&Number.isFinite(x.d)).sort((a,b)=>a.r-b.r);if(!p.length)return null;if(d<=p[0].r)return p[0].d;for(let i=1;i<p.length;i++){const a=p[i-1],b=p[i];if(d<=b.r){if(b.r===a.r)return b.d;const t=(d-a.r)/(b.r-a.r);return a.d+(b.d-a.d)*Math.max(0,Math.min(1,t));}}return p.at(-1).d;}
function sameCurve(a,b,t=.05){const x=(a||[]).map(o=>[Number(o.r),Number(o.d)]),y=(b||[]).map(o=>[Number(o.r),Number(o.d)]);return x.length===y.length&&x.every((v,i)=>near(v[0],y[i][0],.01)&&near(v[1],y[i][1],t));}
function assumed(x){if(!x||typeof x!=='object')return false;if(x.assumed===true)return true;const f=x.assumedFields;if(Array.isArray(f))return f.length>0;if(f&&typeof f==='object')return Object.keys(f).length>0;return false;}
function directLethality(x){if(!x||typeof x!=='object')return false;for(const k of ['damageMult','dmgMult','damageMultiplier','dmgMultiplier','rpmMult','rateOfFireMult','rofMult'])if(k in x){const n=Number(x[k]);if(Number.isFinite(n)&&n!==0&&n!==1)return true;}for(const k of ['damageAdd','dmgAdd','autoRpm'])if(k in x){const n=Number(x[k]);if(Number.isFinite(n)&&n!==0)return true;}return x.setsFireModeAuto===true||x.setsFireModeBurst===true;}
const lowMult=Number(expected.lowBodyMultiplier||.67), legacyIds=['m2010esr','sv98','psr','miniscout','l115'];
for(const [id,def] of Object.entries(expected.weapons||{})){const raw=findWeapon(id,def.name),rows=[];if(!raw){if(id==='interdictor')warnings.push('Interdictor remains absent from upstream analyzer; empirical-current audited model remains active.');else errors.push(`${id}: missing from upstream weapons.json`);}else{if(raw.cls!=='Sniper Rifle')errors.push(`${id}: expected Sniper Rifle, got ${raw.cls}`);if(legacyIds.includes(id)&&!sameCurve(raw.dmg,def.curve))errors.push(`${id}: upstream damage curve no longer matches audited linear curve; manual re-audit required`);if(Number.isFinite(Number(def.bulletVel))&&!near(raw.bulletVel,def.bulletVel,1))errors.push(`${id}: upstream velocity ${raw.bulletVel} != audited ${def.bulletVel}`);if(id==='miniscout'){const effective=60000/Number(raw.rpm)+Number(expected.knownGoodCrossCheck?.miniScoutOfficialMinimumShotTimeIncreaseMs||0);if(!near(effective,Number(def.shotIntervalMs),1))errors.push(`miniscout: effective interval ${effective} != audited ${def.shotIntervalMs}`);if(!near(Number(raw.rpm),Number(expected.knownGoodCrossCheck?.miniScoutRawNominalRpmBeforeMinimumInterval),.2))warnings.push(`Mini Scout upstream nominal RPM changed from 51 to ${raw.rpm}; verify +100ms minimum interval.`);}}
 for(let d=1;d<=300;d++){const damage=linearDamage(def.curve,d),btk=btkFor(damage),ttk=ttkFromInterval(def.shotIntervalMs,btk),lowDamage=damage*lowMult,lowBtk=btkFor(lowDamage),lowTtk=ttkFromInterval(def.shotIntervalMs,lowBtk);if(!(lowBtk>=btk&&lowTtk>=ttk))errors.push(`${id}@${d}m low-body sanity failed`);lowBodyChecks++;if(raw&&legacyIds.includes(id)){const rd=linearDamage(raw.dmg,d);if(!near(rd,damage,.05))errors.push(`${id}@${d}m raw curve ${rd} != audited ${damage}`);upstreamCurveChecks++;}rows.push({d,damage,btk,ttk,lowDamage,lowBtk,lowTtk});}
 checked[id]={name:def.name,metersChecked:rows.length,shotIntervalMs:def.shotIntervalMs,displayRpm:def.displayRpm,first:rows[0],last:rows.at(-1),upstreamPresent:!!raw,confidence:def.confidence||'audited'};}
function oneShotWindow(id,low=false){const def=expected.weapons[id],hits=[];for(let d=1;d<=300;d++)if(btkFor(linearDamage(def.curve,d)*(low?lowMult:1))===1)hits.push(d);return hits.length?[hits[0],hits.at(-1)]:null;}
for(const [id,range] of Object.entries(expected.knownGoodCrossCheck?.sweetSpots||{})){if(['miniscout','interdictorAllBody','interdictorChestObserved'].includes(id))continue;const got=oneShotWindow(id,false);knownGoodChecks++;if(JSON.stringify(got)!==JSON.stringify(range))errors.push(`${id}: chest one-shot window ${JSON.stringify(got)} != ${JSON.stringify(range)}`);}
knownGoodChecks++;if(oneShotWindow('miniscout',false)!==null)errors.push('miniscout: unexpectedly has chest one-shot window');knownGoodChecks++;if(JSON.stringify(oneShotWindow('interdictor',false))!==JSON.stringify(expected.knownGoodCrossCheck.sweetSpots.interdictorChestObserved))errors.push('interdictor: empirical chest one-shot window changed');knownGoodChecks++;if(JSON.stringify(oneShotWindow('interdictor',true))!==JSON.stringify(expected.knownGoodCrossCheck.sweetSpots.interdictorAllBody))errors.push('interdictor: all-body one-shot window changed');
for(const [id,ms] of Object.entries(expected.knownGoodCrossCheck?.effectiveFollowUpMs||{})){const def=expected.weapons[id];knownGoodChecks++;if(!near(Math.round(Number(def.shotIntervalMs)),Number(ms),1))errors.push(`${id}: follow-up ${Math.round(def.shotIntervalMs)} != known-good ${ms}`);}
const catalogs={muzzle:Array.isArray(atts.MUZZLES)?atts.MUZZLES:[],barrel:Array.isArray(atts.BARRELS)?atts.BARRELS:[],grip:Array.isArray(atts.GRIPS)?atts.GRIPS:[],laser:Array.isArray(atts.LASERS)?atts.LASERS:[],light:Array.isArray(atts.LIGHTS)?atts.LIGHTS:[],ergo:Array.isArray(atts.ERGOS)?atts.ERGOS:[]};
for(const id of legacyIds){const def=expected.weapons[id],raw=findWeapon(id,def.name);if(!raw)continue;const wa=atts.WEAPON_ATTS?.[raw.id]||{};for(const slot of ['muzzle','barrel','grip','laser','light'])for(const attId of (Array.isArray(wa[slot])?wa[slot]:[])){const x=catalogs[slot].find(o=>o.id===attId);if(x&&directLethality(x)&&!assumed(x))errors.push(`${id}: verified ${slot} ${attId} changes direct lethality; explicit sniper re-audit required`);}for(const attId of (atts.WEAPON_ERGO?.[raw.id]?.avail||[])){const x=catalogs.ergo.find(o=>o.id===attId);if(x&&directLethality(x)&&!assumed(x))errors.push(`${id}: verified ergo ${attId} changes direct lethality; explicit sniper re-audit required`);}for(const [mid,x] of Object.entries(atts.WEAPON_MAG?.[raw.id]?.mags||{}))if(directLethality(x)&&!assumed(x))errors.push(`${id}: verified magazine ${mid} changes direct lethality; explicit sniper re-audit required`);}
const sniperAmmoIds=new Set();for(const id of legacyIds){const def=expected.weapons[id],raw=findWeapon(id,def.name);if(raw)for(const aid of Object.keys(ammo.WEAPON_AMMO?.[raw.id]?.ammo||{}))sniperAmmoIds.add(aid);}for(const x of (ammo.AMMO||[]))if(sniperAmmoIds.has(x.id)&&directLethality(x)&&!assumed(x))errors.push(`ammo ${x.id}: verified direct sniper lethality modifier detected; explicit re-audit required`);
const report={schema:1,class:'Sniper Rifle',gameVersion:expected.gameVersion,generatedAt:new Date().toISOString(),definition:expected.ttkDefinition,weaponCountExpected:Object.keys(expected.weapons||{}).length,weaponCountChecked:Object.keys(checked).length,fullyVerifiedCount:Number(expected.fullyVerifiedCount||5),empiricalCurrentCount:Number(expected.empiricalCurrentCount||1),metersPerWeapon:300,totalBaseMeterChecks:Object.keys(checked).length*300,lowBodyChecks,upstreamCurveChecks,knownGoodChecks,pass:errors.length===0,errors,warnings,checked,verifiedRules:{allSixCurrentSnipers:true,oneToThreeHundredMeters:true,linearSweetSpotInterpolation:true,officialSweetSpotWindows:true,effectiveBoltCadence:true,miniScoutPlus100msMinimumInterval:true,lowBodyMultiplier067:true,interdictorEmpiricalCurrentModel:true,noGuessedReconRechamberBonus:true,verifiedDirectLethalityRequiresReaudit:true}};
await mkdir(outDir,{recursive:true});await writeFile(join(outDir,'sniper-audit-runtime.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(!report.pass)process.exitCode=2;
